name: Backend Unit Tests Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run tests with coverage for the previous commit
        run: |
          git checkout HEAD^  # Checkout the previous commit
          cd server
          npm test --coverage

      - name: Generate coverage report for previous commit
        run: |
          cd /home/runner/work/address-book/address-book/server/src/tests
          node generate-coverage.js

      - name: Check for coverage summary file from previous commit
        run: |
          if [ ! -f server/coverage/total-coverage.json ]; then
            echo "Coverage summary file not found for previous commit!"
            exit 1
          fi

      - name: Extract previous coverage percentage
        id: extract-previous-coverage
        run: |
          coverage_file="server/coverage/total-coverage.json"
          previous_coverage=$(jq '.lines' $coverage_file)
          echo "Previous Coverage: $previous_coverage"
          echo "previous_coverage=$previous_coverage" >> $GITHUB_ENV

      - name: Checkout the latest commit
        run: |
          git checkout master

      - name: Run tests with coverage for the current commit
        run: |
          cd server
          npm test --coverage  # Run tests with coverage

      - name: Generate coverage report for current commit
        run: |
          cd /home/runner/work/address-book/address-book/server/src/tests
          node generate-coverage.js

      - name: Check for coverage summary file for current commit
        run: |
          if [ ! -f server/coverage/total-coverage.json ]; then
            echo "Coverage summary file not found for current commit!"
            exit 1
          fi

      - name: Extract current coverage percentage
        id: extract-current-coverage
        run: |
          coverage_file="server/coverage/total-coverage.json"
          current_coverage=$(jq '.lines' $coverage_file)
          echo "Current Coverage: $current_coverage"
          echo "current_coverage=$current_coverage" >> $GITHUB_ENV

      - name: Compare coverage
        run: |
          if [[ -n "$previous_coverage" ]]; then
            echo "Previous Coverage: $previous_coverage"
            echo "Current Coverage: $current_coverage"

            # Compare current and previous coverage
            if (( $(echo "$current_coverage < $previous_coverage" | bc -l) )); then
              echo "Coverage decreased! Current: $current_coverage, Previous: $previous_coverage"
              exit 1
            elif (( $(echo "$current_coverage == $previous_coverage" | bc -l) )); then
              echo "Coverage is unchanged. Current: $current_coverage, Previous: $previous_coverage"
            else
              echo "Coverage is acceptable. Current: $current_coverage, Previous: $previous_coverage"
            fi
          else
            echo "No previous coverage data available."
          fi
