name: UI Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: |
          cd client/address-book-ui
          npm install

      - name: Run ESLint
        run: |
          cd client/address-book-ui
          npm run lint
